version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1 #logs
    command: sh -c "python manage.py runserver 0.0.0.0:8000"


  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - backend #Debe correr primero el back