# Generated by Django 5.1.1 on 2024-09-22 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("low", "Low"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="prioridad de la tarea",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("progress", "Progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                            ("expired", "Expired"),
                        ],
                        default="progress",
                        max_length=20,
                        verbose_name="estado de la tarea",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha límite"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tarea",
                "verbose_name_plural": "tareas",
            },
        ),
    ]
